### ISSUE TITLE
action taken by any user should be logged.

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-server#89]
Any action taken by any user should be logged (login, logout, create user, renew session, change password, etc.)

**Comment by mirceaalexandru** [comment]
log also client IP address

**Comment by AdrianRossouw** [comment]
I think we need a separate log table that we log all matching actions to, perhaps with act-id.

We might need to be careful in places though, because we can't just do a json column with the full message.

The other option is to make this part of the v2 api requirements, where we can do explicit action logging as part of the explicit Hapi routes for the entire API.
